[package]
name = "prubybility"
version = "0.1.0"
authors = ["Jacob Lee <jacob@unabridgedsoftware.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3"